### ISSUE TITLE
IllegalStateException in Compose 1.2.0-beta03

### ISSUE THREAD

**Issue by Jolanrensen** [sanjeevirajm/GlideCompose#1]
```
java.lang.IllegalStateException: Asking for intrinsic measurements of SubcomposeLayout layouts is not supported. This includes components that are built on top of SubcomposeLayout, such as lazy lists, BoxWithConstraints, TabRow, etc. To mitigate this:
    - if intrinsic measurements are used to achieve 'match parent' sizing,, consider replacing the parent of the component with a custom layout which controls the order in which children are measured, making intrinsic measurement not needed
    - adding a size modifier to the component, in order to fast return the queried intrinsic measurement.
        at androidx.compose.ui.node.LayoutNode$NoIntrinsicsMeasurePolicy.maxIntrinsicWidth(LayoutNode.kt:455)
        at androidx.compose.ui.node.LayoutNode$NoIntrinsicsMeasurePolicy.maxIntrinsicWidth(LayoutNode.kt:441)
        at androidx.compose.ui.node.IntrinsicsPolicy.maxIntrinsicWidth(IntrinsicsPolicy.kt:50)
        at androidx.compose.ui.node.InnerPlaceable.maxIntrinsicWidth(InnerPlaceable.kt:58)
        at androidx.compose.ui.layout.MeasuringIntrinsics$DefaultIntrinsicMeasurable.measure-BRTryo0(LayoutModifier.kt:202)
        at androidx.compose.foundation.layout.WrapContentModifier.measure-3p2s80s(Size.kt:878)
        at androidx.compose.ui.layout.MeasuringIntrinsics.maxWidth$ui_release(LayoutModifier.kt:167)
        at androidx.compose.ui.layout.LayoutModifier$DefaultImpls.maxIntrinsicWidth(LayoutModifier.kt:92)
        at androidx.compose.foundation.layout.WrapContentModifier.maxIntrinsicWidth(Size.kt:853)
        at androidx.compose.ui.node.ModifiedLayoutNode.maxIntrinsicWidth(ModifiedLayoutNode.kt:68)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.maxIntrinsicWidth(OuterMeasurablePlaceable.kt:183)
        at androidx.compose.ui.node.LayoutNode.maxIntrinsicWidth(LayoutNode.kt:1445)
        at androidx.compose.ui.layout.DefaultIntrinsicMeasurable.measure-BRTryo0(Layout.kt:312)
        at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1.measure-3p2s80s(Box.kt:115)
        at androidx.compose.ui.layout.MeasurePolicy$DefaultImpls.maxIntrinsicWidth(MeasurePolicy.kt:138)
        at androidx.compose.foundation.layout.BoxKt$boxMeasurePolicy$1.maxIntrinsicWidth(Box.kt:95)
        at androidx.compose.ui.node.IntrinsicsPolicy.maxIntrinsicWidth(IntrinsicsPolicy.kt:50)
        at androidx.compose.ui.node.InnerPlaceable.maxIntrinsicWidth(InnerPlaceable.kt:58)
        at androidx.compose.ui.layout.MeasuringIntrinsics$DefaultIntrinsicMeasurable.measure-BRTryo0(LayoutModifier.kt:202)
        at androidx.compose.foundation.layout.WrapContentModifier.measure-3p2s80s(Size.kt:878)
        at androidx.compose.ui.layout.MeasuringIntrinsics.maxWidth$ui_release(LayoutModifier.kt:167)
        at androidx.compose.ui.layout.LayoutModifier$DefaultImpls.maxIntrinsicWidth(LayoutModifier.kt:92)
        at androidx.compose.foundation.layout.WrapContentModifier.maxIntrinsicWidth(Size.kt:853)
        at androidx.compose.ui.node.ModifiedLayoutNode.maxIntrinsicWidth(ModifiedLayoutNode.kt:68)
        at androidx.compose.ui.node.OuterMeasurablePlaceable.maxIntrinsicWidth(OuterMeasurablePlaceable.kt:183)
        at androidx.compose.ui.node.LayoutNode.maxIntrinsicWidth(LayoutNode.kt:1445)
        at androidx.compose.foundation.layout.IntrinsicMeasureBlocks$HorizontalMaxWidth$1$1.invoke(RowColumnImpl.kt:627)
        at androidx.compose.foundation.layout.IntrinsicMeasureBlocks$HorizontalMaxWidth$1$1.invoke(RowColumnImpl.kt:625)
        at androidx.compose.foundation.layout.RowColumnImplKt.intrinsicMainAxisSize(RowColumnImpl.kt:704)
        at androidx.compose.foundation.layout.RowColumnImplKt.intrinsicSize(RowColumnImpl.kt:682)
        at androidx.compose.foundation.layout.RowColumnImplKt.access$intrinsicSize(RowColumnImpl.kt:1)
        at androidx.compose.foundation.layout.IntrinsicMeasureBlocks$HorizontalMaxWidth$1.invoke(RowColumnImpl.kt:625)
        at androidx.compose.foundation.layout.IntrinsicMeasureBlocks$HorizontalMaxWidth$1.invoke(RowColumnImpl.kt:624)
        at androidx.compose.foundation.layout.RowColumnImplKt$rowColumnMeasurePolicy$1.maxIntrinsicWidth(RowColumnImpl.kt:286)
```

**Comment by sanjeevirajm** [comment]
@Jolanrensen can you share the full code?
